version: '3.8'

services:
  node-service:
    build:
      context: ./law-firm-ev-node
    image: node-app:prod
    container_name: node

  backend-service:
    # Construye la imagen con docker-compose
    build: 
      context: ./law-firm-ev-backend
      dockerfile: ./docker/production.Dockerfile # -f
    # Le asigna el nombre de backend-app:prod a la imagen -t
    # image: backend-app:prod
    # Utiliza el archivo .env para las variables de entorno
    env_file:
      - ./law-firm-ev-backend/.env
    # Nombre del contenedor --name
    container_name: bevprod
    # Nombre del host para que se pueda comunicar otros contenedores en vez de usar la ip
    hostname: bevprod
    # Se reiniciará a menos que se detenga
    restart: unless-stopped
    depends_on:
      - node-service
    # Puerto de la aplicación
    expose:
      - 3333
    # ports:
    #   - 3333:3333
    networks:
      - backend-net
    command: npm start

  frontend-service:
    # Construye la imagen con docker-compose
    build: 
      context: ./law-firm-ev-frontend
      dockerfile: ./docker/production.Dockerfile # -f
    # Le asigna el nombre de frontend-app:prod a la imagen -t
    # image: frontend-app:prod
    # Nombre del contenedor --name
    container_name: fevprod
    # Nombre del host para que se pueda comunicar otros contenedores en vez de usar la ip
    hostname: fevprod
    # Se reiniciará a menos que se detenga
    restart: unless-stopped
    depends_on:
      - node-service
      # - backend-service
    # Puerto de la aplicación
    expose:
      - 4000
    # ports:
    #   - 4000:4000
    networks:
      - frontend-net
    command: npm run serve:ssr

  nginx-service:
    build:
      context: ./law-firm-ev-nginx
    # image: nginx-app:prod
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80   # Puerto para http
      - 443:443 # Puerto para https
    volumes:
      - ./law-firm-ev-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./law-firm-ev-nginx/certbot/conf:/etc/letsencrypt
      - ./law-firm-ev-nginx/certbot/www:/var/www/certbot
    depends_on:
      - backend-service
      - frontend-service
    networks:
      - backend-net

  certbot-service:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./law-firm-ev-nginx/certbot/conf:/etc/letsencrypt
      - ./law-firm-ev-nginx/certbot/www:/var/www/certbot
    # --email es el correo electronico para recibir notificaciones
    # --agree-tos acepta los terminos y condiciones
    # --no-eff-email no envia correos electronicos
    # --staging Esto le indica a Certbot que le gustaría utilizar el entorno de prueba de Let's Encrypt para obtener certificados de prueba. El uso de esta opción le permite probar sus opciones de configuración y evitar posibles límites de solicitud de dominio.
    # --force-renewal Esto le indicará a Certbot que desea solicitar un nuevo certificado con los mismos dominios que un certificado existente.
    command: certonly --webroot -w /var/www/certbot --email giovannirm.python@gmail.com --agree-tos --no-eff-email --force-renewal -d api.bufetevaldivieso.com -d www.api.bufetevaldivieso.com
    depends_on:
      - nginx-service
    networks:
      - backend-net
networks:
  backend-net:

  frontend-net: